name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
workers_dev = true
main = "src/index.js"
compatibility_date = "2021-12-07"
routes = [
  { pattern = "docker.vialink.cc", custom_domain = true },
  { pattern = "quey.vialink.cc", custom_domain = true },
  { pattern = "gcr.vialink.cc", custom_domain = true },
  { pattern = "k8s-gcr.vialink.cc", custom_domain = true },
  { pattern = "k8s.vialink.cc", custom_domain = true },
  { pattern = "ghcr.vialink.cc", custom_domain = true },
  { pattern = "cloudsmith.vialink.cc", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
